# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigation_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_navigation_mainwindow(QtWidgets.QMainWindow):
    def setupUi(self, navigation_mainwindow):
        navigation_mainwindow.setObjectName("navigation_mainwindow")
        navigation_mainwindow.resize(1469, 755)
        self.label = QtWidgets.QLabel(navigation_mainwindow)
        self.label.setGeometry(QtCore.QRect(30, 20, 67, 17))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit.setGeometry(QtCore.QRect(30, 50, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 120, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 67, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 190, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 67, 17))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 260, 41, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 330, 113, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_5.setGeometry(QtCore.QRect(30, 300, 67, 17))
        self.label_5.setObjectName("label_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_6.setGeometry(QtCore.QRect(30, 400, 113, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_6.setGeometry(QtCore.QRect(30, 370, 67, 17))
        self.label_6.setObjectName("label_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_7.setGeometry(QtCore.QRect(30, 470, 113, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_7 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_7.setGeometry(QtCore.QRect(30, 440, 67, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_8.setGeometry(QtCore.QRect(30, 510, 67, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_8.setGeometry(QtCore.QRect(30, 540, 113, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_9.setGeometry(QtCore.QRect(30, 580, 67, 17))
        self.label_9.setObjectName("label_9")
        self.lineEdit_9 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_9.setGeometry(QtCore.QRect(30, 610, 113, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_10.setGeometry(QtCore.QRect(160, 50, 113, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_10 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_10.setGeometry(QtCore.QRect(160, 20, 67, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_11.setGeometry(QtCore.QRect(160, 90, 67, 17))
        self.label_11.setObjectName("label_11")
        self.lineEdit_11 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_11.setGeometry(QtCore.QRect(160, 120, 113, 25))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_12.setGeometry(QtCore.QRect(160, 190, 113, 25))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_12 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_12.setGeometry(QtCore.QRect(160, 160, 67, 17))
        self.label_12.setObjectName("label_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_13.setGeometry(QtCore.QRect(160, 260, 51, 25))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_13 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_13.setGeometry(QtCore.QRect(160, 230, 67, 17))
        self.label_13.setObjectName("label_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_14.setGeometry(QtCore.QRect(160, 330, 113, 25))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_14 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_14.setGeometry(QtCore.QRect(160, 300, 67, 17))
        self.label_14.setObjectName("label_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_15.setGeometry(QtCore.QRect(160, 400, 113, 25))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_15 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_15.setGeometry(QtCore.QRect(160, 370, 67, 17))
        self.label_15.setObjectName("label_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_16.setGeometry(QtCore.QRect(160, 470, 113, 25))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_16 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_16.setGeometry(QtCore.QRect(160, 440, 67, 17))
        self.label_16.setObjectName("label_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_17.setGeometry(QtCore.QRect(160, 540, 113, 25))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_17 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_17.setGeometry(QtCore.QRect(160, 510, 67, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_18.setGeometry(QtCore.QRect(220, 260, 67, 17))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_19.setGeometry(QtCore.QRect(80, 260, 16, 17))
        self.label_19.setObjectName("label_19")
        self.lineEdit_18 = QtWidgets.QLineEdit(navigation_mainwindow)
        self.lineEdit_18.setGeometry(QtCore.QRect(100, 260, 41, 25))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.pushButton = QtWidgets.QPushButton(navigation_mainwindow)
        self.pushButton.setGeometry(QtCore.QRect(170, 610, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_20 = QtWidgets.QLabel(navigation_mainwindow)
        self.label_20.setGeometry(QtCore.QRect(30, 650, 71, 17))
        self.label_20.setObjectName("label_20")
        self.comboBox = QtWidgets.QComboBox(navigation_mainwindow)
        self.comboBox.setGeometry(QtCore.QRect(30, 680, 111, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(navigation_mainwindow)
        QtCore.QMetaObject.connectSlotsByName(navigation_mainwindow)

    def retranslateUi(self, navigation_mainwindow):
        _translate = QtCore.QCoreApplication.translate
        navigation_mainwindow.setWindowTitle(_translate("navigation_mainwindow", "Form"))
        self.label.setText(_translate("navigation_mainwindow", "g"))
        self.lineEdit.setText(_translate("navigation_mainwindow", "9.81"))
        self.lineEdit_2.setText(_translate("navigation_mainwindow", "0"))
        self.label_2.setText(_translate("navigation_mainwindow", "x0"))
        self.label_3.setText(_translate("navigation_mainwindow", "y0"))
        self.lineEdit_3.setText(_translate("navigation_mainwindow", "10000"))
        self.label_4.setText(_translate("navigation_mainwindow", "theta0"))
        self.lineEdit_4.setText(_translate("navigation_mainwindow", "20"))
        self.lineEdit_5.setText(_translate("navigation_mainwindow", "400"))
        self.label_5.setText(_translate("navigation_mainwindow", "v0"))
        self.lineEdit_6.setText(_translate("navigation_mainwindow", "40000"))
        self.label_6.setText(_translate("navigation_mainwindow", "xt0"))
        self.lineEdit_7.setText(_translate("navigation_mainwindow", "10000"))
        self.label_7.setText(_translate("navigation_mainwindow", "yt0"))
        self.label_8.setText(_translate("navigation_mainwindow", "thetat0"))
        self.lineEdit_8.setText(_translate("navigation_mainwindow", "0"))
        self.label_9.setText(_translate("navigation_mainwindow", "vt"))
        self.lineEdit_9.setText(_translate("navigation_mainwindow", "-100"))
        self.lineEdit_10.setText(_translate("navigation_mainwindow", "100"))
        self.label_10.setText(_translate("navigation_mainwindow", "m0"))
        self.label_11.setText(_translate("navigation_mainwindow", "P1"))
        self.lineEdit_11.setText(_translate("navigation_mainwindow", "15000"))
        self.lineEdit_12.setText(_translate("navigation_mainwindow", "0"))
        self.label_12.setText(_translate("navigation_mainwindow", "P2"))
        self.lineEdit_13.setText(_translate("navigation_mainwindow", "240"))
        self.label_13.setText(_translate("navigation_mainwindow", "Ip1"))
        self.lineEdit_14.setText(_translate("navigation_mainwindow", "0"))
        self.label_14.setText(_translate("navigation_mainwindow", "Ip2"))
        self.lineEdit_15.setText(_translate("navigation_mainwindow", "4"))
        self.label_15.setText(_translate("navigation_mainwindow", "Tp1"))
        self.lineEdit_16.setText(_translate("navigation_mainwindow", "0"))
        self.label_16.setText(_translate("navigation_mainwindow", "Tp2"))
        self.lineEdit_17.setText(_translate("navigation_mainwindow", "0"))
        self.label_17.setText(_translate("navigation_mainwindow", "mzt"))
        self.label_18.setText(_translate("navigation_mainwindow", "g"))
        self.label_19.setText(_translate("navigation_mainwindow", "/"))
        self.lineEdit_18.setText(_translate("navigation_mainwindow", "180"))
        self.pushButton.setText(_translate("navigation_mainwindow", "start"))
        self.label_20.setText(_translate("navigation_mainwindow", "Algorithm"))
        self.comboBox.setItemText(0, _translate("navigation_mainwindow", "classic"))
        self.comboBox.setItemText(1, _translate("navigation_mainwindow", "RL"))
        self.comboBox.setItemText(2, _translate("navigation_mainwindow", "GA"))

